# Generated by Django 5.1.5 on 2025-02-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0002_remove_cheesetype_name_remove_crusttype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheesetype',
            name='cheese_type',
        ),
        migrations.RemoveField(
            model_name='crusttype',
            name='crust_type',
        ),
        migrations.RemoveField(
            model_name='pizzasize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='saucetype',
            name='sauce_type',
        ),
        migrations.AddField(
            model_name='cheesetype',
            name='name',
            field=models.CharField(default='Mozzarella', max_length=100),
        ),
        migrations.AddField(
            model_name='crusttype',
            name='name',
            field=models.CharField(default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='name',
            field=models.CharField(default='Medium', max_length=100),
        ),
        migrations.AddField(
            model_name='saucetype',
            name='name',
            field=models.CharField(default='Tomato', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizzaOrder.topping'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
