# Generated by Django 5.1.5 on 2025-02-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0003_remove_cheesetype_cheese_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='delivery_time',
        ),
    ]
