# Generated by Django 5.1.5 on 2025-02-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0004_remove_deliverydetail_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='card_expiry_date',
        ),
    ]
