# Generated by Django 5.1.5 on 2025-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0005_remove_deliverydetail_card_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(to='pizzaOrder.topping'),
        ),
    ]
