# Generated by Django 5.1.5 on 2025-02-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0010_pizzaorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='order_id',
        ),
    ]
