# Generated by Django 5.1.5 on 2025-02-03 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0013_alter_pizzaorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='order',
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
